### ISSUE TITLE
Print link: In dark mode the icon is not visible

### ISSUE THREAD

**Issue by ChristineWuerth** [alphagov/govuk_publishing_components#4268] opened 2024-09-26 12:57 UTC
This is an accessibility weakness someone raised with us in the process of documenting the print link component as part of the design documentation work:
This says there might be an accessibility issue: https://components.publishing.service.gov.uk/component-guide/print_link

Calum's view on this:
In dark mode the icon is no longer visible. I don't think it's a compliance accessibility issue as the text remains readable.
there's a Chrome extension called Midnight Lizard which forces a dark mode on the page to view this.

This might be worth improving

**Comment by andysellick** [comment] 2024-09-27 08:16
Just to clarify @ChristineWuerth the accessibility issue raised at https://components.publishing.service.gov.uk/component-guide/print_link is the automated checker saying there 'could' be an issue but it can't determine if there is or isn't. This happens for the automated checker whenever we use a background image, because the concern is that the background image might be under the text and therefore causing an issue, but the automated checker can't interpret the image (it's not that advanced) so it just raises the warning just in case.

We've got a few components where this happens and they're all fine, because we've checked them manually (we only rely on the automated accessibility testing a tiny bit).

Also when you raise these kinds of issues can you be much more specific please? From the way this issue is written it seems like the issue raised by the automated checker is a secondary issue, but the primary issue isn't detailed in any way. If this is two separate issues please raise the other one separately, and please provide full details of what the issue is - all it says is that someone raised it, but doesn't say who or what the issue is. I'm going to close this issue now because we don't support dark mode yet and I don't think an icon missing is a problem - the purpose of the link is primarily determined by the text, which remains visible.

**Closed by andysellick** 2024-09-27 08:16 UTC
