### ISSUE TITLE
Browsers on 3G slow connections make duplicate requests for the fonts

### ISSUE THREAD

**Issue by Nooshu** [alphagov/govuk_publishing_components#597] opened 2018-10-31 16:45 UTC
## Issue
Certain pages on GOV.UK load the font files twice. This has been observed on [this speech page](https://www.gov.uk/government/speeches/spring-statement-2018-philip-hammonds-speech) for 3G Slow connection in both Chrome and Firefox.

![screen shot 2018-10-31 at 16 17 54](https://user-images.githubusercontent.com/1223960/47804204-1f67dc80-dd2c-11e8-8114-cab6d5a86ee3.png)

```
https://assets.publishing.service.gov.uk/government-frontend/light-f38ad40456-v1-b98fe790388f58c950f2bed1ca8ad02fa168d6effa7aae7cb7fee81e51183f46.woff2
https://assets.publishing.service.gov.uk/government-frontend/bold-a2452cb66f-v1-be83c947da6c602697be56d5f04bab2074ad9e8e7fe39807f814654fd691d328.woff2

https://assets.publishing.service.gov.uk/static/fonts/v1-f38ad40456-light-b98fe790388f58c950f2bed1ca8ad02fa168d6effa7aae7cb7fee81e51183f46.woff2
https://assets.publishing.service.gov.uk/static/fonts/v1-a2452cb66f-bold-be83c947da6c602697be56d5f04bab2074ad9e8e7fe39807f814654fd691d328.woff2
```

## Data
Web Page Test data for this issue can be seen here:
- Firefox: https://www.webpagetest.org/result/181030_XS_65068cfbd7c9820c6e26d99d0d4b7535/3/details/#waterfall_view_step1
- Chrome: https://www.webpagetest.org/result/181030_BR_4e44c2d0e3e60b7e4f53114873a0a30f/2/details/#waterfall_view_step1

## Explanation
What I believe is happening is there are 2 `@font-face` rules in the pages CSS. For 3G Slow connections the font isn't being downloaded in time so by the time it gets to the 2nd request the font (`nta`) isn't there, so it downloads it again. So slower connections are being penalised. This doesn't occur in faster connections because the font is already available and the browser doesn't need to trigger the second download.

## Impact
An additional 110KB of data will need to be downloaded on these browsers (246KB in total). This is also skewing our performance results in WPT because the 2nd loading of the font file is creating a Flash of Invisible Text (FOIT) later in the page load. This is extending the 'visually complete' and 'last visual change' metrics (see the graph below) for both HTTP/1 and HTTP/2.

![screen shot 2018-10-31 at 16 18 28](https://user-images.githubusercontent.com/1223960/47804219-2989db00-dd2c-11e8-8c88-5663b6502e1a.png)

## Solution
The ideal solution would be to only have a single `@font-face` declaration used on a page.

**Comment by tijmenb** [comment] 2018-11-01 10:50
This is caused by the components using GOV.UK Frontend's version of the font.

@alex-ju would it be possible to disable GOV.UK Frontend font loading altogether?

**Comment by nickcolley** [comment] 2018-11-01 11:11
This is the upstream bug for this: https://github.com/alphagov/govuk-frontend/issues/1001

Potentially you could do something like:

```scss
$govuk-font-family: "noop-hack", "nta", Arial, sans-serif; // "Custom" font stack; this means design system won't load fonts.
```

**Comment by alex-ju** [comment] 2018-11-01 11:21
I was thinking we can update the font names in static to follow [the naming convention](https://github.com/alphagov/fonts#naming-convention) and then set `$govuk-fonts-path` to reference them from `/static/fonts/`

**Comment by Nooshu** [comment] 2019-03-19 10:05
Issue now fixed and should be visible once upgraded to [GOV.UK Frontend 2.9.0](https://github.com/alphagov/govuk-frontend/releases/tag/v2.9.0).

**Comment by alex-ju** [comment] 2019-03-19 10:08
@Nooshu indeed; will try to prioritise the update and after testing I'll close this one.

**Comment by alex-ju** [comment] 2019-03-29 15:27
@Nooshu as govuk-frontend 2.9.0 was rolled out this is not fixed

**Closed by alex-ju** 2019-03-29 15:27 UTC
Labels: bug
